[package]
name = "enf-tool-box"
version = "0.1.0"
authors = ["Travrei <qjogos7@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

dioxus = { version = "*", features = ["web", "router"] }
reqwest = { version = "*", features = ["blocking", "json"] }
serde_json = "*"

# Debug
dioxus-logger = "*"

[profile]

[profile.wasm-dev]
inherits = "dev"
opt-level = 1

[profile.server-dev]
inherits = "dev"

[profile.android-dev]
inherits = "dev"
