[application]

# App (Project) Name
name = "NurseKit"

# `build` & `serve` dist path
#out_dir = "docs"


[web.app]

# HTML title tag content
title = "NurseKit"
base_path = "/"

# include `assets` in web platform
[web.resource]

# CSS style file

style = [
    "https://fonts.googleapis.com/css2?family=Roboto:wght@400;500;700&display=swap",
    "https://fonts.googleapis.com/icon?family=Material+Icons",
    "https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined",
    "assets/css/materialize.css",
]

# Javascript code file
script = ["assets/js/materialize.js"]

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []
